/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;

import java.awt.Color;

/**
 *
 * @author abhishekvora
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        jMenu_Home.setOpaque(true);
        jMenu_Home.setBackground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Home = new javax.swing.JMenu();
        jMenu_Movies = new javax.swing.JMenu();
        jMenu_Users = new javax.swing.JMenu();
        jMenu_SignUp = new javax.swing.JMenu();
        jMenu_Review = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/abhishekvora/Downloads/cooltext239939720807251.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 10, 280, 140);

        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("The best Offline Movie Database");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 140, 204, 16);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(580, 300, 111, 29);

        jMenu_Home.setText("Home");
        jMenu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HomeMouseClicked(evt);
            }
        });
        jMenu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Home);

        jMenu_Movies.setText("Movies");
        jMenu_Movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_MoviesMouseClicked(evt);
            }
        });
        jMenu_Movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MoviesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Movies);

        jMenu_Users.setText("Users");
        jMenu_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_UsersMouseClicked(evt);
            }
        });
        jMenu_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_UsersActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Users);

        jMenu_SignUp.setText("Sign Up");
        jMenu_SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SignUpMouseClicked(evt);
            }
        });
        jMenu_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SignUpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_SignUp);

        jMenu_Review.setText("Review");
        jMenu_Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ReviewMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Review);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jMenu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_HomeActionPerformed
        
    }//GEN-LAST:event_jMenu_HomeActionPerformed

    private void jMenu_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_UsersActionPerformed
        
    }//GEN-LAST:event_jMenu_UsersActionPerformed

    private void jMenu_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SignUpActionPerformed
        
    }//GEN-LAST:event_jMenu_SignUpActionPerformed

    private void jMenu_MoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MoviesActionPerformed
        
    }//GEN-LAST:event_jMenu_MoviesActionPerformed

    private void jMenu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HomeMouseClicked

    }//GEN-LAST:event_jMenu_HomeMouseClicked

    private void jMenu_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_UsersMouseClicked
       UsersPage frame = new UsersPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_UsersMouseClicked

    private void jMenu_SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SignUpMouseClicked
        UserRegistration frame = new UserRegistration();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_SignUpMouseClicked

    private void jMenu_MoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MoviesMouseClicked
        MovieList frame = new MovieList();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_MoviesMouseClicked

    private void jMenu_ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ReviewMouseClicked
        ReviewsPage frame = new ReviewsPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_ReviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenu_Home;
    private javax.swing.JMenu jMenu_Movies;
    private javax.swing.JMenu jMenu_Review;
    private javax.swing.JMenu jMenu_SignUp;
    private javax.swing.JMenu jMenu_Users;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
