/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author abhishekvora
 */
public class ReviewsPage extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement stmt;
    int mem_id;
    
    public ReviewsPage() {
        initComponents();
        
        jMenu_Review.setOpaque(true);
        jMenu_Review.setBackground(Color.lightGray);
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String db,unm,pwd;
            db="jdbc:mysql://localhost:3306/dbs_project";
            unm="root";
            pwd="root";
            con=DriverManager.getConnection(db,unm,pwd);
            stmt=con.createStatement();
            
            String qry,name;
            Vector comboBoxItems=new Vector();
            qry = "select m_name,m_id from movie";
            rs = stmt.executeQuery(qry);
            while(rs.next())
            {
                name = rs.getString("m_name");
                comboBoxItems.add(name);
            }    
            DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
            cmbMovieName.setModel(model);
            
            
            
            this.setSize(750,540);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtMemId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbMovieName = new javax.swing.JComboBox<>();
        lblM_Id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReview = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        rdb5 = new javax.swing.JRadioButton();
        rdb3 = new javax.swing.JRadioButton();
        rdb4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Home = new javax.swing.JMenu();
        jMenu_Movies = new javax.swing.JMenu();
        jMenu_Users = new javax.swing.JMenu();
        jMenu_SignUp = new javax.swing.JMenu();
        jMenu_Review = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 80, 90, 16);

        txtMemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtMemId);
        txtMemId.setBounds(240, 70, 292, 26);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Movie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 160, 70, 16);

        cmbMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovieNameActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMovieName);
        cmbMovieName.setBounds(240, 160, 294, 27);

        lblM_Id.setBackground(new java.awt.Color(153, 0, 0));
        lblM_Id.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblM_Id.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblM_Id);
        lblM_Id.setBounds(560, 120, 140, 27);

        txtReview.setColumns(20);
        txtReview.setRows(5);
        jScrollPane1.setViewportView(txtReview);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 260, 358, 146);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Review:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 270, 110, 16);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(340, 430, 88, 29);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rating: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 210, 70, 16);

        buttonGroup1.add(rdb1);
        rdb1.setText("1");
        getContentPane().add(rdb1);
        rdb1.setBounds(220, 200, 40, 23);

        buttonGroup1.add(rdb2);
        rdb2.setText("2");
        getContentPane().add(rdb2);
        rdb2.setBounds(270, 200, 40, 23);

        buttonGroup1.add(rdb5);
        rdb5.setText("5");
        getContentPane().add(rdb5);
        rdb5.setBounds(420, 200, 40, 23);

        buttonGroup1.add(rdb3);
        rdb3.setText("3");
        getContentPane().add(rdb3);
        rdb3.setBounds(320, 200, 40, 23);

        buttonGroup1.add(rdb4);
        rdb4.setText("4");
        getContentPane().add(rdb4);
        rdb4.setBounds(370, 200, 40, 23);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 0, 86, 29);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 120, 90, 16);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(240, 110, 292, 26);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/abhishekvora/Desktop/feedback.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-50, 0, 800, 590);

        jMenu_Home.setText("Home");
        jMenu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HomeMouseClicked(evt);
            }
        });
        jMenu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Home);

        jMenu_Movies.setText("Movies");
        jMenu_Movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_MoviesMouseClicked(evt);
            }
        });
        jMenu_Movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MoviesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Movies);

        jMenu_Users.setText("Users");
        jMenu_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_UsersMouseClicked(evt);
            }
        });
        jMenu_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_UsersActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Users);

        jMenu_SignUp.setText("Sign Up");
        jMenu_SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SignUpMouseClicked(evt);
            }
        });
        jMenu_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SignUpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_SignUp);

        jMenu_Review.setText("Review");
        jMenu_Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ReviewMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Review);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemIdActionPerformed

    private void cmbMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovieNameActionPerformed
        try
        {
            String qry;
            qry = "select m_id from movie where m_name = '"+String.valueOf(cmbMovieName.getSelectedItem())+"'";
            rs = stmt.executeQuery(qry);
            rs.first();
            mem_id = Integer.parseInt(rs.getString("m_ID"));
            lblM_Id.setText("Movie Id: "+mem_id);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_cmbMovieNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try
        {
            String qry,qry2,qry3,qry4,qry5,qry6,u_id,review,pass;
            u_id=txtMemId.getText();
            review = txtReview.getText();
            pass = String.valueOf(txtPassword.getPassword());
            int rating = 0;
            cmbMovieName.setSelectedIndex(0);
            if(rdb1.isSelected())
                rating = 1;
            else if(rdb2.isSelected())
                rating = 2;
            else if(rdb3.isSelected())
                rating = 3;
            else if(rdb4.isSelected())
                rating = 4;
            else if(rdb5.isSelected())
                rating = 5;
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter a rating!!!!");
                return;
            }
            if(txtReview.getText() == "")
            {
                JOptionPane.showMessageDialog(null, "Please enter a Review!!!!");
                return;
            }
            qry2 = "select * from user where u_id = "+u_id;
            rs = stmt.executeQuery(qry2);
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null, "No such user exists");
                return;
            }
            rs.first();
            if(!pass.equals(rs.getString("password")))
            {
                JOptionPane.showMessageDialog(null, "Wrong username or password");
                return;
            }
            qry4 = "select count(*) from reviews where u_id="+u_id+" and m_id="+mem_id;
            rs = stmt.executeQuery(qry4);
            rs.first();
            if(Integer.parseInt(rs.getString("count(*)")) != 0)
            {
                
                qry5 = "update reviews set review = '"+review+"' where u_id = "+u_id+" and m_id="+mem_id;
                qry6 = "update reviews set rating = '"+rating+"' where u_id = "+u_id+" and m_id="+mem_id;
                stmt.executeUpdate(qry5);
                stmt.executeUpdate(qry6);
                JOptionPane.showMessageDialog(null, "Your review has been updated");
                this.dispose();
                Home frame = new Home();
                frame.setVisible(true);
                return;
            }
            
            qry="insert into reviews values("+u_id+","+mem_id+",'"+review+"',"+rating+")";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(null, "Thank you for the feedback!");
            
            this.dispose();
            Home frame = new Home();
            frame.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
            
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home frame = new Home();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HomeMouseClicked
        Home frame = new Home();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_HomeMouseClicked

    private void jMenu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_HomeActionPerformed

    }//GEN-LAST:event_jMenu_HomeActionPerformed

    private void jMenu_MoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MoviesMouseClicked
        MovieList frame = new MovieList();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_MoviesMouseClicked

    private void jMenu_MoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MoviesActionPerformed

    }//GEN-LAST:event_jMenu_MoviesActionPerformed

    private void jMenu_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_UsersMouseClicked
        UsersPage frame = new UsersPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_UsersMouseClicked

    private void jMenu_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_UsersActionPerformed

    }//GEN-LAST:event_jMenu_UsersActionPerformed

    private void jMenu_SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SignUpMouseClicked
        UserRegistration frame = new UserRegistration();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_SignUpMouseClicked

    private void jMenu_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SignUpActionPerformed

    }//GEN-LAST:event_jMenu_SignUpActionPerformed

    private void jMenu_ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ReviewMouseClicked
        ReviewsPage frame = new ReviewsPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_ReviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbMovieName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Home;
    private javax.swing.JMenu jMenu_Movies;
    private javax.swing.JMenu jMenu_Review;
    private javax.swing.JMenu jMenu_SignUp;
    private javax.swing.JMenu jMenu_Users;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblM_Id;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    private javax.swing.JRadioButton rdb3;
    private javax.swing.JRadioButton rdb4;
    private javax.swing.JRadioButton rdb5;
    private javax.swing.JTextField txtMemId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextArea txtReview;
    // End of variables declaration//GEN-END:variables
}
