/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedatabase;
import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abhishekvora
 */
public class UsersPage extends javax.swing.JFrame {
    
    Connection con;
    ResultSet rs;
    Statement stmt;
    int i=1;

    public UsersPage() {
        initComponents();
        
        jMenu_Users.setOpaque(true);
        jMenu_Users.setBackground(Color.lightGray);
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String db,unm,pwd;
            db="jdbc:mysql://localhost:3306/dbs_project";
            unm="root";
            pwd="root";
            con=DriverManager.getConnection(db,unm,pwd);
            stmt=con.createStatement();
            
            this.setSize(794, 444);
            //this.getContentPane().setBackground( Color.darkgray);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        btnfirst = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnprevious = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnload = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Home = new javax.swing.JMenu();
        jMenu_Movies = new javax.swing.JMenu();
        jMenu_Users = new javax.swing.JMenu();
        jMenu_SignUp = new javax.swing.JMenu();
        jMenu_Review = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtUserName);
        txtUserName.setBounds(360, 110, 258, 26);
        getContentPane().add(txtcontact);
        txtcontact.setBounds(360, 190, 258, 26);

        btnfirst.setText("<<<");
        btnfirst.setEnabled(false);
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnfirst);
        btnfirst.setBounds(210, 320, 80, 29);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member ID");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 60, 125, 22);

        btnprevious.setText("<");
        btnprevious.setEnabled(false);
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnprevious);
        btnprevious.setBounds(310, 320, 87, 29);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date Of Membership");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 150, 150, 22);

        btndelete.setText("DELETE");
        btndelete.setEnabled(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(260, 280, 90, 29);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Name");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 110, 125, 22);

        btnload.setText("LOAD");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnload);
        btnload.setBounds(370, 280, 80, 29);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contact");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 190, 177, 22);

        txtid.setEditable(false);
        getContentPane().add(txtid);
        txtid.setBounds(360, 60, 258, 26);

        btnnext.setText(">");
        btnnext.setEnabled(false);
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        getContentPane().add(btnnext);
        btnnext.setBounds(400, 320, 90, 29);

        txtdate.setEditable(false);
        txtdate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdate.setAlignmentX(2.0F);
        getContentPane().add(txtdate);
        txtdate.setBounds(360, 150, 258, 26);

        btnupdate.setText("UPDATE");
        btnupdate.setEnabled(false);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(460, 280, 94, 29);

        btnlast.setText(">>>");
        btnlast.setEnabled(false);
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });
        getContentPane().add(btnlast);
        btnlast.setBounds(500, 320, 94, 29);

        jButton1.setText("New User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 240, 103, 29);

        logo.setIcon(new javax.swing.ImageIcon("/Users/abhishekvora/Desktop/member.gif")); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(0, 0, 800, 420);

        jMenu_Home.setText("Home");
        jMenu_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HomeMouseClicked(evt);
            }
        });
        jMenu_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Home);

        jMenu_Movies.setText("Movies");
        jMenu_Movies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_MoviesMouseClicked(evt);
            }
        });
        jMenu_Movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_MoviesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Movies);

        jMenu_Users.setText("Users");
        jMenu_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_UsersMouseClicked(evt);
            }
        });
        jMenu_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_UsersActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Users);

        jMenu_SignUp.setText("Sign Up");
        jMenu_SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SignUpMouseClicked(evt);
            }
        });
        jMenu_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SignUpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_SignUp);

        jMenu_Review.setText("Review");
        jMenu_Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_ReviewMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Review);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        try{
            rs.first();
            txtid.setText(rs.getString("u_ID"));
            txtUserName.setText(rs.getString("Name"));
            txtcontact.setText(rs.getString("Contact"));
            txtdate.setText(rs.getString("date_mem"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        try{
            rs.previous();
            txtid.setText(rs.getString("u_id"));
            txtUserName.setText(rs.getString("Name"));
            txtcontact.setText(rs.getString("Contact"));
            txtdate.setText(rs.getString("date_mem"));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "End of results");
            try {
                rs.next();
            } catch (SQLException ex) {
                
            }
        }
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try
        {
            String qry,id;
            id=txtid.getText();
            qry="delete from user where u_id="+id;
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(null, "Successfully Deleted!!!!!!");
            
            txtUserName.setText("");
            txtcontact.setText("");
            txtdate.setText("");
            txtid.setText("");
            
            btnlast.setEnabled(false);
            btnfirst.setEnabled(false);
            btnprevious.setEnabled(false);
            btnnext.setEnabled(false);
            btndelete.setEnabled(false);
            btnupdate.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        try
        {
            String qry="select * from user";
            rs=stmt.executeQuery(qry);
            rs.first();
            txtUserName.setText(rs.getString("name"));
            txtcontact.setText(rs.getString("Contact"));
            txtdate.setText(rs.getString("date_mem"));
            txtid.setText(rs.getString("u_ID"));
            
            btnlast.setEnabled(true);
            btnfirst.setEnabled(true);
            btnprevious.setEnabled(true);
            btnnext.setEnabled(true);
            btndelete.setEnabled(true);
            btnupdate.setEnabled(true);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnloadActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        try{
            rs.next();
            txtid.setText(rs.getString("u_id"));
            txtUserName.setText(rs.getString("Name"));
            txtcontact.setText(rs.getString("Contact"));
            txtdate.setText(rs.getString("date_mem"));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "End of results");
            try {
                rs.previous();
            } catch (SQLException ex) {
                
            }
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try
        {
            String qry,id,name,date,address,contact;
            name=txtUserName.getText();
            id=txtid.getText();
            date=txtdate.getText();
            contact=txtcontact.getText();
            qry="Update user set Name='"+name+"',date_mem='"+date+"',Contact="+contact+" where u_id="+id;
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(null, "Successfully Updated!!!!!!");
            
            txtUserName.setText("");
            txtcontact.setText("");
            txtdate.setText("");
            txtid.setText("");
            
            btnlast.setEnabled(false);
            btnfirst.setEnabled(false);
            btnprevious.setEnabled(false);
            btnnext.setEnabled(false);
            btndelete.setEnabled(false);
            btnupdate.setEnabled(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        try{
            rs.last();
            txtid.setText(rs.getString("u_id"));
            txtUserName.setText(rs.getString("Name"));
            txtcontact.setText(rs.getString("Contact"));
            txtdate.setText(rs.getString("date_mem"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnlastActionPerformed

    private void jMenu_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HomeMouseClicked
        Home frame = new Home();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_HomeMouseClicked

    private void jMenu_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_HomeActionPerformed

    }//GEN-LAST:event_jMenu_HomeActionPerformed

    private void jMenu_MoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_MoviesMouseClicked
        MovieList frame = new MovieList();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_MoviesMouseClicked

    private void jMenu_MoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_MoviesActionPerformed

    }//GEN-LAST:event_jMenu_MoviesActionPerformed

    private void jMenu_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_UsersMouseClicked
        UsersPage frame = new UsersPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_UsersMouseClicked

    private void jMenu_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_UsersActionPerformed

    }//GEN-LAST:event_jMenu_UsersActionPerformed

    private void jMenu_SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SignUpMouseClicked
        UserRegistration frame = new UserRegistration();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_SignUpMouseClicked

    private void jMenu_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SignUpActionPerformed

    }//GEN-LAST:event_jMenu_SignUpActionPerformed

    private void jMenu_ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_ReviewMouseClicked
        ReviewsPage frame = new ReviewsPage();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenu_ReviewMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserRegistration frame = new UserRegistration();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Home;
    private javax.swing.JMenu jMenu_Movies;
    private javax.swing.JMenu jMenu_Review;
    private javax.swing.JMenu jMenu_SignUp;
    private javax.swing.JMenu jMenu_Users;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
